version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: NGINX_COIMA
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./study/:/var/www/html"
      - "./config/nginx/site.conf:/etc/nginx/conf.d/site.conf"
      - "./config/nginx/logs:/var/log/nginx/"
      - "./config/ssl:/etc/nginx/ssl"
    depends_on:
      - php
    links:
      - php
    networks:
      - study-subnet

  php:
    build:
      context: ./config/php
    container_name: PHP_7.2_COIMA
    volumes:
      - "./study/:/var/www/html"
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - study-subnet

  mariadb:
    image: mariadb
    container_name: MariaDB_COIMA
    #restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        #volumes:
        #- "./config/mariaDB/dump/:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    networks:
      study-subnet:
        ipv4_address: 172.28.0.2

networks:
  study-subnet:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"
